# TODO: uniquement utilisé pour le dev/les tests
# à supprimer quand on déployera le code chez le "client"

version: "3"

services:
    web1:
        image: dockercloud/hello-world
        container_name: web1
        ports:
            - "81:80"
    web2:
        image: dockercloud/hello-world
        container_name: web2
        ports:
            - "82:80"
