global:


route:
  group_by: ['instance', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  routes:
  - match:
      alertname: InstanceDown
  receiver: 'alert-team'

receivers:
- name: 'alert-team'
  email_configs:
  - to: "dieu.mibu@gmail.com"
    from: 'dieu.mibu@gmail.com'
    smarthost: smtp.gmail.com:587
    auth_username: 'dieu.mibu@gmail.com'
    auth_password: 'saphiros'

