



- name: download grafana
  shell: wget https://dl.grafana.com/oss/release/grafana_8.1.5_amd64.deb

- name: trigger sudo
  shell: echo password | sudo -S echo "bob"

- name: install grafana
  shell: sudo dpkg -i grafana_8.1.5_amd64.deb
  ignore_errors: yes
  
- name: fix install
  shell: sudo apt -y --fix-broken install 

- name: delete grafana_8.1.5_amd64.deb
  file:
    path: grafana_8.1.5_amd64.deb
    state: absent

- name: Start grafana service
  service:
    name: grafana-server
    state: started
    enabled: yes

- name: Check if grafana is accessible
  uri:
    url: http://localhost:3000
    method: GET
    status_code: 200
